### ISSUE TITLE
async node require

### ISSUE THREAD

**Issue by PinkaminaDianePie** [caridy/loader.js#1]
i know, in node `require` is synchronous, but i just found awesome lib for solving this: https://github.com/abbr/deasync
this lib can turn any async function to sync, so with it you can make your loader much more closer to spec :)

**Comment by caridy** [comment]
@PinkaminaDianePie we do have a solution in place for node to load ES Standard Modules synchronous, while the loader will be available for those who want to import modules just like they will do in a browser environment. All these is possible because node has access to the internals of the V8, not need to use a library of any sort.
